### ISSUE TITLE
How to get status of sended message

### ISSUE THREAD

**Issue by maksakoviliya** [nutnetru/laravel-sms#10]
How to chech if sms was sent? Or has been delivered?

**Comment by maximkou** [comment]
Hi! 

Sms was accepted by provider, when `send` or` sendBatch` returns `true` (not actual for IqSms Ru - this provider throws exception). In most cases it's mean "sms was sent/will be sent".

Package at this moment has not delivery status checks. You can extend SmsSender and sms provider classes, to add this functionality in your project.

**Comment by maksakoviliya** [comment]
Думаю можно на русском) 
Спасибо за ответ!
Было критично знать статус - поэтому использовал только сам класс [zelenin/sms_ru](https://github.com/zelenin/sms_ru). По сути Ваше приложение просто проксирует методы основной библиотеки.
