### ISSUE TITLE
Неправильный алиас iqsms

### ISSUE THREAD

**Issue by streeboga** [nutnetru/laravel-sms#11]
Везде в конфигах указано iqsmsru и документации, а в сервис-провайдере подключается, как iqsms.
Если поправить в своем конфиге и в .env то всё работает хорошо, спасибо за ваш труд :)

**Comment by maximkou** [comment]
Спасибо вам, что не прошли мимо и рассказали о проблеме! 
Мы внесли исправления, они доступны с версии 0.9.1
