### ISSUE TITLE
Support "zelenin/smsru": "~5"

### ISSUE THREAD

**Issue by bigperson** [nutnetru/laravel-sms#12]
Too few arguments to function Zelenin\SmsRu\Api::__construct(), 1 passed in .../vendor/nutnet/laravel-sms/src/Providers/SmsRu.php on line 92 and exactly 2 expected

**Comment by maximkou** [comment]
Hello, @bigperson!

I created PR #13 which adds support for new version of `zelenin/smsru`, but I need little help from you: can you checkout `support_smsru_v5` branch and check sms sending (currently I don't have an account in sms.ru and no posibility to check that)?
